### ISSUE TITLE
Prepared Statements and Multiple Statements

### ISSUE THREAD

**Issue by dankell** [midnightcodr/hapi-mysql2#2]
We're currently in the process of reviewing a move from Hapi16 to Hapi17 and we're looking at using hapi-mysql2 

One issue we've run into is with multiple statements versus prepared statements. As far as I can see hapi-mysq2 supports multiple statements when using the `request.mysql.pool.query()` syntax. 

According to the node-mysql [docs](https://github.com/sidorares/node-mysql2#using-prepared-statements) it will escape queries when `connection.execute` is used rather than `connection.query`.

**However** in testing it appears that `connection.execute` _does not_ support multiple statements. 

Is this the case or am I missing something?

**Comment by midnightcodr** [comment]
I don't think it's possible that you can prepare/execute multiple statements. This is the limitation of mysql, not node-mysql2. Please take a look at https://stackoverflow.com/questions/20371677/execute-multiple-semi-colon-separated-query-using-mysql-prepared-statement

**Comment by midnightcodr** [comment]
There's a difference in the underlying working of `.query()` and `.execute()`, the former uses client-side escape while the later is done through the server. I asked the author of node-mysql2 about potential sql injection vulnerability using `.query()` and it seems pretty safe to use: https://github.com/sidorares/node-mysql2/issues/712

**Comment by dankell** [comment]
Thought it might be an issue with node-mysql2 rather than hapi-mysql2 (In fact I thought I'd said something to that effect, but obviously forgot...)

Thanks for chasing this down for me.
